### PR TITLE
added install doc

### PR DESCRIPTION
**Pull request by jpoeana1**
Created a file called INSTALL.md which gives instructions on  what to download and how to get started.

### CODE REVIEW

**Comment by JKuiper7** [comment]
I wrote the portion on how to install xampp!

**Comment by HussainMohsin** [comment]
The ability to add our project to the navigation bar through the index.html for xampp, made it easier and quicker to access and view our front-end part of the project. PhpMyAdmin was also in the navigation bar which allowed accessing the database much simpler.

**Comment by AdhamOudeif** [comment]
Xampp is a great resouce that consolidates many processes into one. Database, SQL, Local servers, etc.

**Comment by douhaalemara** [comment]
I found it very convenient that I was able to make some changes on my local repository and view the changes I made simply through XAMPP before pushing them onto the remote repository. This helped keep things organized for the group and allowed us to keep a good work-flow.

**Comment by douhaalemara** [comment]
I have been switching between BBEdit text editor and visual studio code. I feel like visual studio code keeps my files a bit more organized, but I have always been using BBEdit for my past classes so I’m a little more familiar with it.

**Comment by sjiang1** [comment]
I think the "Running XAMPP" portion is about how to run a Mac version of Xampp. Is that correct? Is the whole document for a Mac version?

**Comment by sjiang1** [comment]
`<li class="">< target="_blank" href="your repo link here">Repo Name</a></li>`
should be 
`<li class=""><a target="_blank" href="your repo link here">Repo Name</a></li>`

**Comment by dillonKilroy** [comment]
I am not sure if it is just me but I am seeing funky characters where I think a single quote should be.

**Comment by dillonKilroy** [comment]
For line 14 where it talks about needing certain things to be installed. I was wondering if we should recommend installing phpMyAdmin also so that you wouldn't have to go through a terminal to access the database. If that isn't something that is installed right away when you choose to install php. Another thing that I remember for Mac at least was that the initial startup came up with a prompt that initialized the app. I really like the last bit about getting phpMyAdmin running on a Mac. That was something that Brandon and I had to spend a good amount of time last year trying to figure out. The whole Install doc looks great and walks you through everything you would need to get up and running!

**Pull request merged**
