### PR TITLE
Updated FileSystem

### PR DESCRIPTION
**Pull request by DAguilar1998**
Fixed the filesystem to fit the php and github standard.
Following the standard used here: https://github.com/php-pds/skeleton

- Moved all our source code to the src folder.
- Created a testing folder for testing code.
- Created a public folder to handle our server code.
- Added a .gitignore file to ignore trash files generated by the operating system.
- Added the GPL3 license file.
- Added a changelog file with everything that has been completed.

### CODE REVIEW

**Comment by dillonKilroy** [comment]
Pages folder holds all the php source code for our app.

**Comment by HussainMohsin** [comment]
Styles folder Is the folder that contains our style.css, which helps us design our front end

**Comment by jpoeana1** [comment]
The client folder contains all the files for the webpage that are needed for the client side, or user's device.

**Comment by JKuiper7** [comment]
The test folder will hold our files for testing code

**Comment by Bstaton321** [comment]
The includes folder is the folder that contains the php to connect to the database

**Comment by AdhamOudeif** [comment]
ChangeLog file contains a log of commits made by contributors, and includes each persons hex ID

**Comment by douhaalemara** [comment]
The src folder contains all the includes, pages, style sub folders

**Comment by sjiang1** [comment]
> The client folder contains all the files for the webpage that are needed for the client side, or user's device.

I don't think you have a client folder now!

**Comment by jpoeana1** [comment]
Thank you Professor for pointing that out. I read the wrong branch. 
The Public folder will contain all the web server files.

**Comment by DAguilar1998** [comment]
The license file contains the GPL3 license which allows anyone to utilize, distribute, or modify our code. However, it does not make us liable if our code were to cause damage to the user.

**Pull request merged**
