### PR TITLE
DAguilar Organized the Project

### PR DESCRIPTION
**Pull request by DAguilar1998**
Filesystem has been organized.

### CODE REVIEW

**Comment by JKuiper7** [comment]
Test folder will hold the test code for our test suite

**Comment by dillonKilroy** [comment]
Pages folder holds all the php source code for our app

**Comment by AdhamOudeif** [comment]
ChangeLog file contains a list of all commits by users, and includes their hex ID

**Comment by HussainMohsin** [comment]
Styles folder Is the folder that contains our style.css, which helps us design our front end

**Comment by Bstaton321** [comment]
The includes folder is the folder that contains the php to connect to the database

**Pull request closed without merging**
